version: '3'
services:
  jenkins:
    user: jenkins
    image: jenkins_jcasc:${JENKINS_VERSION}
    container_name: jenkins
    ports: 
      - 8080:8080
    environment:
      JENKINS_SERVER: ${JENKINS_SERVER}
      JENKINS_ADMIN_ID: ${JENKINS_ADMIN_ID}
      JENKINS_ADMIN_PASSWORD: ${JENKINS_ADMIN_PASSWORD}
      COMPANY_NAME: ${COMPANY_NAME}
      GITHUB_PASS: ${GITHUB_PASS}
      GITHUB_USER: ${GITHUB_USER}
    volumes:
      - ./casc_docker.yaml:/var/jenkins_home/casc.yaml
      - /var/run/docker.sock:/var/run/docker.sock
  
  registry:
    image: registry:2
    container_name: registry
    ports:
      - 5001:5000