version: '3'
services:
  jenkins:
    image: jenkins_jcasc:${JENKINS_VERSION}
    container_name: jenkins
    ports: 
      - 8080:8080
    environment:
      JENKINS_SERVER: ${JENKINS_SERVER}
      JENKINS_ADMIN_ID: ${JENKINS_ADMIN_ID}
      JENKINS_ADMIN_PASSWORD: ${JENKINS_ADMIN_PASSWORD}
      COMPANY_NAME: ${COMPANY_NAME}
    volumes:
      - ./casc.yaml:/var/jenkins_home/casc.yaml